/** US States for credit application State dropdowns (50 states + DC). */
export const US_STATES: { value: string; label: string }[] = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];

/** Housing options for Step 1 (Required). */
export const HOUSING_OPTIONS: { value: string; label: string }[] = [
  { value: 'own', label: 'Own' },
  { value: 'rent', label: 'Rent' },
  { value: 'live_with_relatives', label: 'Live with Relatives' },
];

/** Consultant options for Step 5 (Required). */
export const CONSULTANT_OPTIONS: { value: string; label: string }[] = [
  { value: '', label: 'Select consultant' },
  { value: 'henry_liu', label: 'Henry Liu' },
  { value: 'christopher_amico', label: 'Christopher Amico' },
  { value: 'michael_minerva', label: 'Michael Minerva' },
  { value: 'vicky_azrak', label: 'Vicky Azrak' },
  { value: 'james_dai', label: 'James Dai' },
  { value: 'aaron_cui', label: 'Aaron Cui' },
  { value: 'abby_gorani', label: 'Abby Gorani' },
  { value: 'bobby_kaufman', label: 'Bobby Kaufman' },
  { value: 'christine_reich', label: 'Christine Reich' },
  { value: 'derek_anton', label: 'Derek Anton' },
  { value: 'daniel_jay_lehrer', label: 'Daniel Jay Lehrer' },
  { value: 'jeffrey_horn', label: 'Jeffrey Horn' },
  { value: 'mark_onbashian', label: 'Markin DeLacruz' },
  { value: 'markin', label: 'Markin' },
  { value: 'michael_zeitoune', label: 'Michael Zeitoune' },
  { value: 'michael_van_houten', label: 'Michael Van Houten' },
  { value: 'rafael_frias', label: 'Rafael Frias' },
  { value: 'ricky_wong', label: 'Ricky Wong' },
  { value: 'rushi_sanghavi', label: 'Rushi Sanghavi' },
  { value: 'sarah_flynn', label: 'Sarah Flynn' },
  { value: 'stephen_jo', label: 'Stephen Jo' },
  { value: 'wilson_dong', label: 'Wilson Dong' },
  { value: 'finance_team', label: 'Finance Team' },
  { value: 'yehuda_cohen', label: 'Yehuda Cohen' },
  { value: 'other', label: 'Other' },
];

/** Email mapping for consultants */
export const CONSULTANT_EMAIL_MAP: Record<string, string> = {
  'henry_liu': 'henry@capitalmotorcars.com',
  'christopher_amico': 'camico@capitalmotorcars.com',
  'michael_minerva': 'mike.minerva@capitalmotorcars.com',
  'vicky_azrak': 'vicky@capitalmotorcars.com',
  'james_dai': 'james@capitalmotorcars.com',
  'aaron_cui': 'info@capitalmotorcars.com',
  'abby_gorani': 'info@capitalmotorcars.com',
  'bobby_kaufman': 'bobby@capitalmotorcars.com',
  'christine_reich': 'info@capitalmotorcars.com',
  'derek_anton': 'derek@capitalmotorcars.com',
  'daniel_jay_lehrer': 'dlehrer@capitalmotorcars.com',
  'jeffrey_horn': 'jeffrey@capitalmotorcars.com',
  'mark_onbashian': 'mark@capitalmotorcars.com',
  'markin': 'mark@capitalmotorcars.com',
  'michael_zeitoune': 'mzeitoune@capitalmotorcars.com',
  'michael_van_houten': 'mvanhouten@capitalmotorcars.com',
  'rafael_frias': 'rafael@capitalmotorcars.com',
  'ricky_wong': 'ricky@capitalmotorcars.com',
  'rushi_sanghavi': 'info@capitalmotorcars.com',
  'sarah_flynn': 'sarah@capitalmotorcars.com',
  'stephen_jo': 'info@capitalmotorcars.com',
  'wilson_dong': 'info@capitalmotorcars.com',
  'finance_team': 'info@capitalmotorcars.com',
  'yehuda_cohen': 'info@capitalmotorcars.com',
  'other': 'info@capitalmotorcars.com',
};

/** Get consultant email by value */
export const getConsultantEmail = (consultantValue: string): string => {
  return CONSULTANT_EMAIL_MAP[consultantValue] || 'info@capitalmotorcars.com';
};
