-- Create vehicle_types table
CREATE TABLE IF NOT EXISTS public.vehicle_types (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  body_style text NOT NULL,
  image_url text,
  vehicle_name text NOT NULL,
  description text,
  starting_price numeric,
  fuel_types text[],
  drivetrain text[],
  passenger_capacity integer,
  cargo_space text,
  fuel_economy jsonb,
  performance jsonb,
  specs jsonb,
  feature_groups jsonb,
  highlights text[],
  popular_brands text[],
  ideal_for text[],
  features text[],
  badge text,
  meta_title text,
  meta_description text,
  is_luxury boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  display_category text,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.vehicle_types ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public can view vehicle types"
  ON public.vehicle_types FOR SELECT
  USING (true);

CREATE POLICY "Admins can manage vehicle types"
  ON public.vehicle_types FOR ALL
  USING (auth.role() = 'authenticated');

-- Seed Data
INSERT INTO public.vehicle_types (
  slug, name, body_style, image_url, vehicle_name, description, starting_price, 
  fuel_types, drivetrain, passenger_capacity, cargo_space, 
  fuel_economy, performance, specs, feature_groups, 
  highlights, popular_brands, ideal_for, features, badge, 
  meta_title, meta_description, is_luxury, sort_order
) VALUES
(
  'cayenne-e-hybrid', 
  'Hybrid SUV', 
  'SUV', 
  '/vehicle-images/cayanne.png', 
  'Porsche Cayenne E-Hybrid', 
  'The best of both worlds. The Cayenne E-Hybrid pairs a turbocharged V6 with a potent electric motor, delivering 463 hp and the ability to handle daily commutes on pure electricity.', 
  1962.89, 
  ARRAY['gasoline', 'electric'], 
  ARRAY['AWD'], 
  5, 
  'large', 
  '{"city": 17, "hwy": 23, "avg": 19, "range": 430}', 
  '{"hp": 463, "torque": 479, "engine": "3.0L Turbo V6 PHEV", "transmission": "8-Speed Tiptronic S", "drivetrain": "All-Wheel Drive", "zeroToSixty": "4.6 sec"}', 
  '{"exterior": {"length": "194.1″", "height": "66.8″", "weight": "5,348 lbs", "wheels": "20\" AeroDesign"}, "interior": {"headroom": "39.6″", "legroom": "41.2″", "cargo": "22.1 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / 50k miles"}}', 
  '[{"category": "Hybrid Tech", "items": ["25.9 kWh Battery", "11kW On-board Charger", "E-Power & Hybrid Modes"]}, {"category": "Handling", "items": ["PASM (Active Suspension)", "Power Steering Plus", "Optional Rear-Axle Steering"]}, {"category": "Cabin", "items": ["12.6-inch Curved Display", "12.3-inch PCM", "Matrix LED Headlights"]}]', 
  ARRAY['48-Mile Electric Range', '463 HP Combined Output', '11kW AC Charging'], 
  ARRAY['BMW', 'Mercedes-Benz', 'Lexus', 'Toyota', 'Honda', 'Porsche'], 
  ARRAY['Eco-conscious drivers not ready for a full EV', 'Families needing 7,700+ lbs of towing capacity', 'Daily commuters looking to drive gas-free on weekdays'], 
  ARRAY['3.0L V6 Turbo combined with 174 hp Electric Motor', '12.6-inch Curved Digital Instrument Cluster', 'Standard PASM (Porsche Active Suspension Management)', 'Warn & Brake Assist with Pedestrian Protection', 'Available 10.9-inch Passenger Side Display'], 
  'PHEV Performance', 
  '2026 Porsche Cayenne E-Hybrid Leasing', 
  'Lease the versatile and powerful 2026 Porsche Cayenne E-Hybrid plug-in SUV.', 
  true, 
  1
),
(
  'corvette-z06-1lz', 
  'American Hypercar Coupe', 
  'Coupe', 
  '/vehicle-images/corvette.png', 
  'Chevrolet Corvette Z06 1LZ', 
  'The soul of a race car in a street-legal body. The Z06 features the hand-assembled LT6 V8—the most powerful naturally aspirated production V8 in history.', 
  2272.85, 
  ARRAY['gasoline'], 
  ARRAY['RWD'], 
  2, 
  'small', 
  '{"city": 12, "hwy": 21, "avg": 15, "range": 278}', 
  '{"hp": 670, "torque": 460, "engine": "5.5L LT6 V8 (Flat-Plane Crank)", "transmission": "8-Speed Dual-Clutch (DCT)", "drivetrain": "Rear-Wheel Drive", "zeroToSixty": "2.6 sec"}', 
  '{"exterior": {"length": "184.6″", "height": "48.6″", "weight": "3,500 lbs", "wheels": "20\" Front / 21\" Rear Forged Aluminum"}, "interior": {"headroom": "37.9″", "legroom": "42.8″", "cargo": "12.6 cu. ft.", "passengers": 2}, "warranty": {"comprehensive": "3 years / 36k miles", "powertrain": "5 years / 60k miles", "roadside": "5 years / 60k miles"}}', 
  '[{"category": "Performance", "items": ["Magnetic Ride Control 4.0", "Performance Exhaust", "8,600 RPM Redline"]}, {"category": "Interior", "items": ["GT1 Bucket Seats", "Bose® 10-Speaker Audio", "8-way Power Seats"]}, {"category": "Technology", "items": ["12.7-inch Touchscreen", "14-inch Digital Cluster", "Wireless Charging Pad"]}]', 
  ARRAY['670 HP Naturally Aspirated V8', '2.6s 0-60 mph', 'Flat-Plane Crank Sound'], 
  ARRAY['Porsche', 'BMW', 'Mercedes-Benz', 'Corvette'], 
  ARRAY['Driving purists seeking a high-revving, naturally aspirated V8', 'Track enthusiasts wanting a mid-engine platform with razor-sharp handling', 'Supercar buyers looking for exotic performance at an American price point'], 
  ARRAY['5.5L LT6 V8 Engine with 8,600 RPM Redline', 'Bose® Premium 10-Speaker Audio System', 'Magnetic Selective Ride Control™ 4.0', '12.7-inch Infotainment Screen with Google Built-In', 'Removable Body-Color Roof Panel'], 
  'Track Ready', 
  '2026 Corvette Z06 1LZ Leasing & Specs', 
  'Lease the 670 horsepower naturally aspirated 2026 Corvette Z06 1LZ.', 
  true, 
  2
),
(
  'sedan-mercedes-e350', 
  'Sedan', 
  'Sedan', 
  '/vehicle-images/sedan-mercedes.png', 
  'AMG E 53 4MATIC Sedan', 
  'The benchmark of luxury. The 2026 E 350 features the MBUX Superscreen and a 48V mild-hybrid system for seamless power delivery.', 
  1510.10, 
  ARRAY['gasoline'], 
  ARRAY['AWD'], 
  5, 
  'medium', 
  '{"city": 24, "hwy": 33, "avg": 27, "range": 470}', 
  '{"hp": 255, "torque": 295, "engine": "2.0L I-4 Turbo w/ Mild Hybrid", "transmission": "9G-TRONIC 9-Speed Automatic", "drivetrain": "4MATIC All-Wheel Drive", "zeroToSixty": "6.1 sec"}', 
  '{"exterior": {"length": "194.9″", "height": "58.3″", "weight": "4,198 lbs", "wheels": "18\" 5-Spoke Standard"}, "interior": {"headroom": "37.9″", "legroom": "41.5″", "cargo": "12.7 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / 50k miles"}}', 
  '[{"category": "Tech", "items": ["MBUX Superscreen", "Selfie Camera", "AI Routine Learning"]}, {"category": "Safety", "items": ["PRE-SAFE Impulse Side", "Active Brake Assist", "Car-to-X Comm."]}]', 
  ARRAY['MBUX Superscreen', '48V Mild Hybrid', '4MATIC AWD'], 
  ARRAY['BMW', 'Mercedes', 'Audi', 'Lexus', 'Genesis', 'Toyota', 'Honda', 'Acura', 'Cadillac', 'Alfa Romeo', 'Mazda'], 
  ARRAY['Corporate executives prioritizing comfort and status', 'Tech-forward drivers who want AI-assisted features', 'Small families looking for top-tier safety ratings'], 
  ARRAY['MBUX Superscreen with Passenger Display', 'AI-Powered "Routines" (Automation for Climate/Music)', '64-Color Active Ambient Lighting (Syncs with Sound)', 'Burmester® 4D Surround Sound with Dolby Atmos', 'Digital Vehicle Key (iPhone/Watch compatible)'], 
  NULL, 
  '2026 Mercedes E 350 Sedan Leasing', 
  'Lease the tech-forward 2026 Mercedes-Benz E-Class.', 
  true, 
  3
),
(
  'm8-coupe-competition', 
  'Coupe', 
  'Coupe', 
  '/vehicle-images/bmw.png', 
  'BMW M8 Coupe Competition', 
  'The pinnacle of BMW M engineering. The M8 Competition combines grand touring luxury with a 617-hp V8 and the advanced M xDrive system for supercar-level performance.', 
  2178.80, 
  ARRAY['gasoline'], 
  ARRAY['AWD'], 
  4, 
  'small', 
  '{"city": 15, "hwy": 22, "avg": 17, "range": 342}', 
  '{"hp": 617, "torque": 553, "engine": "4.4L TwinPower Turbo V8", "transmission": "8-Speed M Steptronic", "drivetrain": "M xDrive AWD (with 2WD mode)", "zeroToSixty": "3.0 sec"}', 
  '{"exterior": {"length": "191.8″", "height": "53.6″", "weight": "4,295 lbs", "wheels": "20\" M Star-Spoke"}, "interior": {"headroom": "38.9″", "legroom": "42.1″ (Front)", "cargo": "14.8 cu. ft.", "passengers": 4}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / Unlimited"}}', 
  '[{"category": "M Dynamics", "items": ["M xDrive with 2WD Mode", "Active M Differential", "Adaptive M Suspension"]}, {"category": "Luxury", "items": ["Merino Leather", "Harman Kardon® 16-Speaker", "Carbon Fiber Roof"]}, {"category": "Advanced Tech", "items": ["Live Cockpit Professional", "Laserlight Headlights", "M Track Mode"]}]', 
  ARRAY['617 HP Twin-Turbo V8', '3.0s 0-60 mph', 'M xDrive AWD System'], 
  ARRAY['Porsche', 'BMW', 'Mercedes-Benz', 'Lexus', 'Toyota', 'Honda'], 
  ARRAY['High-performance enthusiasts who want a "track-ready" grand tourer', 'Executives who demand an aggressive presence and top-tier luxury', 'Drivers looking for supercar acceleration with everyday usability'], 
  ARRAY['M xDrive with selectable 2WD mode for pure RWD feel', 'BMW Laserlight Headlights for superior night visibility', 'Adaptive M Suspension for optimized track and street comfort', 'Harman Kardon® 16-speaker Surround Sound System', 'Carbon Fiber Reinforced Plastic (CFRP) Roof for weight reduction'], 
  'Flagship M', 
  '2026 BMW M8 Coupe Competition Leasing', 
  'Experience the 617-hp 2026 BMW M8 Competition. The ultimate luxury athlete.', 
  true, 
  4
),
(
  'sedan-rs-etron-gt', 
  'Electric', 
  'Electric Sedan', 
  '/vehicle-images/electric.png', 
  'Audi RS e-tron GT', 
  'The pinnacle of Audi electric performance. With 912-hp and a 0-60 mph time of just 2.4 seconds, the RS e-tron GT Performance is the most powerful production Audi ever built.', 
  3017.77, 
  ARRAY['electric'], 
  ARRAY['AWD'], 
  5, 
  'small', 
  '{"city": 85, "hwy": 82, "avg": 84, "range": 278}', 
  '{"hp": 912, "torque": 612, "engine": "Dual-Motor Electric (97.0 kWh usable)", "transmission": "2-Speed Automatic (Rear), 1-Speed (Front)", "drivetrain": "quattro All-Wheel Drive with Torque Vectoring", "zeroToSixty": "2.4 sec"}', 
  '{"exterior": {"length": "196.7″", "height": "54.9″", "weight": "5,162 lbs", "wheels": "21\" 5-Spoke RS Design"}, "interior": {"headroom": "38.2″", "legroom": "41.9″", "cargo": "9.2 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / Unlimited"}}', 
  '[{"category": "Electric Performance", "items": ["800V Architecture", "320kW DC Fast Charging", "Launch Control", "Single-Pedal Driving"]}, {"category": "Luxury & Audio", "items": ["16-Speaker Bang & Olufsen 3D Sound", "18-Way Massage Seats", "Carbon Fiber Roof", "Nappa Leather"]}, {"category": "Driver Assist", "items": ["Remote Park Assist Plus", "360° View Camera", "Adaptive Cruise Assist", "Intersection Assist"]}]', 
  ARRAY['912 HP Electric quattro', '2.4s 0-60 MPH', '800V Ultra-Fast Charging'], 
  ARRAY['BMW', 'Mercedes-Benz', 'Audi', 'Genesis', 'Porsche', 'Dodge'], 
  ARRAY['Tech-forward enthusiasts seeking the ultimate electric grand tourer', 'Luxury buyers wanting hypercar acceleration with sedan practicality', 'Drivers prioritizing ultra-fast charging and advanced thermal management'], 
  ARRAY['Bang & Olufsen® 3D Premium Sound System', 'Audi Virtual Cockpit with RS Performance Layout', '18-Way Power Front Sport Seats with Massage and Ventilation', 'Matrix LED Headlights with Audi Laser Light', 'Panoramic Carbon Fiber Roof and Active Rear Spoiler'], 
  'New', 
  '2026 Audi RS e-tron GT Performance Leasing', 
  'Lease the 912-hp Audi RS e-tron GT Performance. 0-60 in 2.4 seconds with ultra-fast charging.', 
  true, 
  5
),
(
  'sedan-750e', 
  'Hybrid', 
  'Sedan', 
  '/vehicle-images/hybrid.png', 
  'BMW 750e xDrive', 
  'The pinnacle of BMW’s electrified luxury. The 750e xDrive combines a silky-smooth 3.0L inline-six with a powerful electric motor for silent city cruising and effortless highway power.', 
  1685.13, 
  ARRAY['gasoline', 'electric'], 
  ARRAY['AWD'], 
  5, 
  'medium', 
  '{"city": 68, "hwy": 74, "avg": 70, "range": 470}', 
  '{"hp": 483, "torque": 516, "engine": "3.0L Turbo 6-Cylinder Plug-in Hybrid", "transmission": "8-Speed Steptronic Sport", "drivetrain": "xDrive Intelligent AWD", "zeroToSixty": "4.6 sec"}', 
  '{"exterior": {"length": "212.2″", "height": "60.8″", "weight": "5,331 lbs", "wheels": "20\" M Aero Bicolor"}, "interior": {"headroom": "39.8″", "legroom": "42.8″ (Rear)", "cargo": "18.5 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / Unlimited"}}', 
  '[{"category": "Electrification", "items": ["34 Mile Electric Range", "7.4kW Onboard Charger", "Regenerative Braking"]}, {"category": "Luxury", "items": ["Bowers & Wilkins Surround Sound", "Panoramic Sky Lounge LED Roof", "Merino Leather Seating"]}, {"category": "Technology", "items": ["BMW Interaction Bar", "Live Cockpit Pro", "Augmented Reality Nav"]}]', 
  ARRAY['483 HP Hybrid System', '34 Mile EV Range', 'BMW Theater Screen Available'], 
  ARRAY['BMW', 'Mercedes-Benz', 'Lexus', 'Toyota', 'Honda'], 
  ARRAY['Eco-conscious executives who want zero-emission city commuting', 'Long-distance travelers requiring high fuel efficiency and range', 'Tech enthusiasts looking for the MBUX-rivalling Interaction Bar'], 
  ARRAY['BMW Interaction Bar with Dynamic Ambient Lighting', 'Panoramic Sky Lounge LED Roof with 1st and 2nd Row Sunroof', '18-Speaker Bowers & Wilkins Surround Sound System', 'Soft-Close Automatic Doors and Power Liftgate', 'Digital Key Plus for smartphone-based vehicle access'], 
  NULL, 
  '2026 BMW 750e xDrive PHEV Leasing', 
  'Lease the 483hp BMW 750e xDrive. Experience 34 miles of pure electric range in the ultimate luxury sedan.', 
  true, 
  6
),
(
  'f150-regular-cab-xl', 
  'Truck', 
  'Truck', 
  '/vehicle-images/raptor.png', 
  'Ford F-150 Regular Cab XL', 
  'The quintessential workhorse. Featuring a massive 8-foot bed, a fuel-efficient 2.7L EcoBoost V6, and advanced towing tech, it’s built for those who value utility and reliability.', 
  676.80, 
  ARRAY['gasoline'], 
  ARRAY['RWD'], 
  3, 
  'extra-large', 
  '{"city": 19, "hwy": 25, "avg": 21, "range": 756}', 
  '{"hp": 325, "torque": 400, "engine": "2.7L EcoBoost V6", "transmission": "10-Speed Automatic", "drivetrain": "Rear-Wheel Drive", "zeroToSixty": "6.0 sec"}', 
  '{"exterior": {"length": "227.7″", "height": "75.2″", "weight": "4,396 lbs", "wheels": "17\" Steel"}, "interior": {"headroom": "40.8″", "legroom": "43.9″", "cargo": "8'' 2\" Bed", "passengers": 3}, "warranty": {"comprehensive": "3 years / 36k miles", "powertrain": "5 years / 60k miles", "roadside": "5 years / 60k miles"}}', 
  '[{"category": "Utility", "items": ["8'' 2\" Long Bed", "7,400 lbs Towing", "1,775 lbs Payload"]}, {"category": "Technology", "items": ["12\" Touchscreen", "Apple CarPlay / Android Auto", "5G Wi-Fi Hotspot"]}, {"category": "Safety", "items": ["Pre-Collision Assist", "BLIS (Blind Spot Info)", "Lane-Keeping System"]}]', 
  ARRAY['8.2-Foot Cargo Bed', '325 HP Twin-Turbo V6', '12-inch SYNC 4 Display'], 
  ARRAY['Ford', 'Chevrolet', 'Ram'], 
  ARRAY['Fleet operators and tradespeople needing maximum bed length', 'Solo contractors looking for a high-tech but rugged workhorse', 'Drivers prioritizing utility and towing over passenger count'], 
  ARRAY['2.7L EcoBoost V6 Engine', 'Class IV Trailer Hitch', '12-inch Digital Instrument Cluster', 'Automatic Emergency Braking', 'Active Grille Shutters'], 
  NULL, 
  '2026 Ford F-150 Regular Cab XL Leasing', 
  'Lease the ultimate long-bed work truck with 325 HP and 7,400 lbs towing capacity.', 
  false, 
  7
),
(
  'hatchback', 
  'Hatchback', 
  'hatchback', 
  '/vehicle-images/audi.png', 
  'Audi S5 Sportback Premium quattro', 
  'The all-new 2026 S5 Sportback merges executive luxury with blistering performance. Redesigned with a 362 HP V6 and a sophisticated "panoramic stage" digital interior, it remains the ultimate versatile sport sedan.', 
  1141.96, 
  ARRAY['premium unleaded'], 
  ARRAY['AWD'], 
  5, 
  'medium', 
  '{"city": 20, "hwy": 29, "avg": 23, "range": 352}', 
  '{"hp": 362, "torque": 406, "engine": "3.0L TFSI Turbo V6", "transmission": "7-Speed S tronic Dual-Clutch", "drivetrain": "quattro® All-Wheel Drive", "zeroToSixty": "4.3 sec"}', 
  '{"exterior": {"length": "187.2″", "height": "54.5″", "weight": "3,924 lbs", "wheels": "19\" 5-Double-V-Spoke"}, "interior": {"headroom": "37.7″", "legroom": "41.3″", "cargo": "21.8 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / unlimited miles"}}', 
  '[{"category": "Performance", "items": ["quattro® AWD", "S Sport Suspension", "Red Brake Calipers"]}, {"category": "Tech", "items": ["14.5-inch MMI Touchscreen", "11.9-inch Virtual Cockpit", "Adaptive Cruise Assist"]}, {"category": "Luxury", "items": ["Panoramic Glass Roof", "Heated Steering Wheel", "Diamond-Stitched Sport Seats"]}]', 
  ARRAY['362 HP Turbo V6', '4.3s 0-60 MPH', 'quattro® AWD System'], 
  ARRAY['Volkswagen', 'Audi', 'BMW', 'Mercedes-Benz', 'Lexus', 'Toyota', 'Honda'], 
  ARRAY['Executives who demand performance without sacrificing 4-door utility', 'Tech-forward drivers looking for the latest "Digital Stage" interior', 'Driving enthusiasts needing year-round capability via quattro AWD'], 
  ARRAY['3.0L TFSI® V6 Engine with 362 HP', '14.5-inch MMI® center touch display', 'Adaptive Cruise Control with Traffic Jam Assist', 'Power Liftgate for hatchback utility', 'Panoramic Roof with variable light control'], 
  NULL, 
  '2026 Audi S5 Sportback Leasing', 
  'Lease the redesigned 2026 Audi S5 Sportback with 362 HP and quattro AWD.', 
  false, 
  8
),
(
  'suv', 
  'SUV', 
  'SUV', 
  '/vehicle-images/suv.png', 
  'Mercedes-AMG GLA 35 4MATIC SUV', 
  'The AMG GLA 35 balances compact versatility with high-performance engineering, featuring a 302-hp turbocharged engine and agile 4MATIC All-Wheel Drive.', 
  842.11, 
  ARRAY['gasoline'], 
  ARRAY['AWD'], 
  5, 
  'large', 
  '{"city": 22, "hwy": 30, "avg": 25, "range": 338}', 
  '{"hp": 302, "torque": 295, "engine": "2.0L Turbo 4-Cylinder Mild Hybrid", "transmission": "8-Speed Dual Clutch Sequential (DCT)", "drivetrain": "4MATIC® All-Wheel Drive", "zeroToSixty": "5.1 sec"}', 
  '{"exterior": {"length": "174.6″", "height": "62.5″", "weight": "3,869 lbs", "wheels": "19\" AMG 10-Spoke"}, "interior": {"headroom": "39.0″", "legroom": "41.0″", "cargo": "50.5 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / 50k miles"}}', 
  '[{"category": "Performance", "items": ["AMG Sport Suspension", "Sport Exhaust System", "4MATIC AWD with Descent Control"]}, {"category": "Luxury", "items": ["Panoramic Glass Roof", "64-Color Ambient Lighting", "Burmester® Surround Sound"]}, {"category": "Technology", "items": ["MBUX with AI Voice Control", "10.25-inch Digital Cluster", "Wireless Charging"]}]', 
  ARRAY['302 HP AMG Engine', '0-60 in 5.1 Seconds', 'MBUX Infotainment System'], 
  ARRAY['Range Rover', 'BMW', 'Mercedes', 'Lexus', 'Acura', 'Infinity', 'Cadillac', 'GMC', 'Jaguar', 'Maserati', 'Alfa Romeo', 'Mazda'], 
  ARRAY['Driving enthusiasts needing a compact yet powerful SUV', 'Urban professionals looking for a stylish, high-performance daily driver', 'Small families who value advanced safety and sporty dynamics'], 
  ARRAY['AMG Sport Exhaust with driver-controlled valve flaps', 'Burmester® Surround Sound System with 12 speakers', 'Panoramic Electric Glass Moonroof', 'Heated and Ventilated Front Sports Seats with 14-way adjustment', 'Active Brake Assist and Blind Spot Assist for maximum safety'], 
  'Best Seller', 
  '2026 AMG GLA 35 4MATIC SUV Leasing', 
  'Experience performance and luxury with the 2026 AMG GLA 35 SUV.', 
  true, 
  9
),
(
  'minivan', 
  'minivan', 
  'Minivan', 
  '/vehicle-images/minivan-odyssey.png', 
  'Honda Odyssey EX-L', 
  'The 2026 Odyssey EX-L balances premium comfort with legendary utility. Featuring a refreshed 9-inch touchscreen and wireless smartphone integration, it remains the ultimate tool for busy families.', 
  626.86, 
  ARRAY['gasoline'], 
  ARRAY['FWD'], 
  8, 
  'large', 
  '{"city": 19, "hwy": 28, "avg": 22, "range": 430}', 
  '{"hp": 280, "torque": 262, "engine": "3.5L i-VTEC V6", "transmission": "10-Speed Automatic", "drivetrain": "Front-Wheel Drive", "zeroToSixty": "6.4 sec"}', 
  '{"exterior": {"length": "205.2″", "height": "69.6″", "weight": "4,526 lbs", "wheels": "18\" Machined Alloy"}, "interior": {"headroom": "38.7″", "legroom": "40.9″", "cargo": "155.8 cu. ft.", "passengers": 8}, "warranty": {"comprehensive": "3 years / 36k miles", "powertrain": "5 years / 60k miles", "roadside": "3 years / 36k miles"}}', 
  '[{"category": "Interior", "items": ["Leather-Trimmed Seats", "Magic Slide® 2nd-Row", "Tri-Zone Climate"]}, {"category": "Technology", "items": ["9-inch Color Touchscreen", "Wireless Apple CarPlay", "CabinTalk® Intercom"]}, {"category": "Safety", "items": ["Honda Sensing® Suite", "Blind Spot Information", "Rear Seat Reminder"]}]', 
  ARRAY['8-Passenger Leather Interior', 'Magic Slide® 2nd-Row Seats', 'Wireless Phone Charger'], 
  ARRAY['Honda', 'Toyota', 'Chrysler', 'RAM'], 
  ARRAY['Large families requiring flexible 8-passenger seating', 'Daily carpoolers who prioritize ease of entry and exit', 'Road trippers looking for a quiet V6 engine and high safety ratings'], 
  ARRAY['Magic Slide® 2nd-Row Seats with Walk-in Feature', 'Power Tailgate with Programmable Height', 'Smart Entry with Walk Away Auto Lock®', 'Heated Front Seats with 12-Way Power Driver Adjustment', 'One-Touch Power Moonroof with Tilt'], 
  'Family Choice', 
  '2026 Honda Odyssey EX-L Leasing', 
  'Lease the 2026 Honda Odyssey EX-L. The most reliable 8-passenger family van.', 
  false, 
  10
),
(
  'wagon', 
  'Wagon', 
  'Wagon', 
  '/vehicle-images/wagon.png', 
  'BMW M5 Touring', 
  'The return of the long-roof legend. The 2026 M5 Touring combines a monstrous 717-hp electrified V8 with high-end executive luxury and enough cargo space for a cross-country sprint.', 
  2174.41, 
  ARRAY['gasoline', 'plug-in hybrid'], 
  ARRAY['AWD'], 
  5, 
  'large', 
  '{"city": 52, "hwy": 57, "avg": 54, "range": 450}', 
  '{"hp": 717, "torque": 738, "engine": "4.4L Twin-Turbo V8 Plug-in Hybrid", "transmission": "8-Speed M Steptronic", "drivetrain": "M xDrive All-Wheel Drive", "zeroToSixty": "3.5 sec"}', 
  '{"exterior": {"length": "200.6″", "height": "59.7″", "weight": "5,530 lbs", "wheels": "20\"/21\" M Double-Spoke"}, "interior": {"headroom": "40.7″", "legroom": "41.3″", "cargo": "16.5 - 57.6 cu. ft.", "passengers": 5}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / Unlimited"}}', 
  '[{"category": "Performance", "items": ["Adaptive M Suspension", "M Compound Brakes", "Active M Differential"]}, {"category": "Tech", "items": ["BMW Curved Display", "Operating System 8.5", "Charging Rate up to 11kW"]}, {"category": "Luxury", "items": ["Bowers & Wilkins Surround Sound", "Panoramic Sky Lounge", "M Multifunction Seats"]}]', 
  ARRAY['717 HP Hybrid V8', '3.5s 0-60 MPH', 'M xDrive AWD System'], 
  ARRAY['BMW M', 'Audi RS', 'Mercedes-AMG'], 
  ARRAY['Performance purists who refuse to sacrifice family utility', 'Tech-savvy drivers wanting high-performance electrification', 'Collectors seeking the first M5 wagon ever offered in the U.S.'], 
  ARRAY['M Hybrid Power Unit with 717 HP', 'Adaptive M Suspension with electronically controlled dampers', '14.9-inch BMW Curved Display with M-specific graphics', 'Bowers & Wilkins 18-speaker Surround Sound System', 'Carbon Fiber Interior Trim and M Leather Steering Wheel'], 
  NULL, 
  '2026 BMW M5 Touring Leasing', 
  'Lease the ultra-high-performance 2026 BMW M5 Touring wagon.', 
  false, 
  11
),
(
  'crossover', 
  'Crossover', 
  'SUV', 
  '/vehicle-images/cuv.png', 
  'Lexus GX 550 Premium', 
  'A rugged icon reborn. The 2026 GX 550 Premium combines a potent 349-hp twin-turbo V6 with a sophisticated 14-inch touchscreen and legendary body-on-frame capability.', 
  940.72, 
  ARRAY['gasoline'], 
  ARRAY['4WD'], 
  7, 
  'medium', 
  '{"city": 15, "hwy": 21, "avg": 17, "range": 357}', 
  '{"hp": 349, "torque": 479, "engine": "3.4L Twin-Turbo V6", "transmission": "10-Speed Automatic", "drivetrain": "Full-Time 4WD", "zeroToSixty": "6.5 sec"}', 
  '{"exterior": {"length": "197.0″", "height": "75.6″", "weight": "5,585 lbs", "wheels": "20\" Alloy"}, "interior": {"headroom": "39.4″", "legroom": "41.2″", "cargo": "76.9 cu. ft. (Max)", "passengers": 7}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "6 years / 70k miles", "roadside": "4 years / Unlimited"}}', 
  '[{"category": "Off-Road", "items": ["Full-Time 4WD", "Torsen® Center Diff", "8,000 lbs Towing"]}, {"category": "Luxury", "items": ["NuLuxe® Trim", "Heated/Ventilated Seats", "Ambient Lighting"]}, {"category": "Tech", "items": ["14.0-inch Display", "Wireless Apple CarPlay", "Lexus Safety System+ 3.0"]}]', 
  ARRAY['349 HP Twin-Turbo V6', 'Full-Time 4WD System', '14-inch Touchscreen'], 
  ARRAY['Lexus', 'BMW', 'Audi', 'Volvo'], 
  ARRAY['Outdoor enthusiasts requiring high-capacity towing and 4WD', 'Families looking for a safe, 3-row luxury SUV with a commanding view', 'Luxury buyers wanting a "go-anywhere" vehicle with refined road manners'], 
  ARRAY['Lexus Interface with 14.0-inch Touchscreen Display', 'Heated and Ventilated 8-Way Power Front Seats', 'Full-Time 4WD with Torsen® Limited-Slip Center Differential', 'Lexus Safety System+ 3.0 with Pedestrian Detection', 'Power Tilt-and-Slide Moonroof with Roof Rails'], 
  'Adventure Luxury', 
  '2026 Lexus GX 550 Premium Leasing', 
  'Lease the all-new 2026 Lexus GX 550. Unmatched luxury meets off-road dominance.', 
  true, 
  12
),
(
  '911-gts-hybrid-cabriolet', 
  'Hybrid Convertible', 
  'Convertible', 
  '/vehicle-images/porschee.png', 
  'Porsche 911 Carrera GTS Cabriolet', 
  'The first-ever electrified 911. The GTS T-Hybrid utilizes a motorsport-derived 3.6L flat-six and an electric exhaust gas turbocharger to eliminate lag and provide instantaneous torque.', 
  3449.57, 
  ARRAY['gasoline', 'hybrid'], 
  ARRAY['RWD'], 
  4, 
  'small', 
  '{"city": 17, "hwy": 23, "avg": 19, "range": 315}', 
  '{"hp": 532, "torque": 449, "engine": "3.6L T-Hybrid Flat-6", "transmission": "8-Speed PDK Dual-Clutch", "drivetrain": "Rear-Wheel Drive", "zeroToSixty": "3.0 sec"}', 
  '{"exterior": {"length": "179.3″", "height": "50.9″", "weight": "3,724 lbs", "wheels": "20\" Front / 21\" Rear GTS Center-Lock"}, "interior": {"headroom": "38.0″", "legroom": "41.6″", "cargo": "4.8 cu. ft. (Frunk)", "passengers": 4}, "warranty": {"comprehensive": "4 years / 50k miles", "powertrain": "4 years / 50k miles", "roadside": "4 years / 50k miles"}}', 
  '[{"category": "T-Hybrid Tech", "items": ["Electric Turbocharger", "400V High-Voltage System", "Energy Recuperation"]}, {"category": "Chassis", "items": ["Rear-Axle Steering", "PASM Sport Suspension", "Sport Chrono Package"]}, {"category": "Digital", "items": ["12.6-inch Curved Display", "Apple CarPlay® Integration", "Matrix LED Headlights"]}]', 
  ARRAY['3.0s 0-60 mph', 'Electrified Turbocharger', 'Standard Rear-Axle Steering'], 
  ARRAY['Porsche', 'BMW', 'Mercedes-Benz', 'Corvette'], 
  ARRAY['Tech-forward enthusiasts wanting the latest in hybrid performance', 'Drivers looking for supercar-rivaling acceleration in a convertible', 'Porsche purists who want the most powerful GTS ever produced'], 
  ARRAY['T-Hybrid Powertrain with Integrated Starter Generator', 'Electric exhaust gas turbocharger for instant response', 'Standard Rear-Axle Steering for enhanced agility', 'Fully Digital 12.6-inch Curved Instrument Cluster', 'Sport Exhaust System with high-gloss black tailpipes'], 
  'T-Hybrid', 
  '2026 Porsche 911 Carrera GTS Hybrid Leasing', 
  'Lease the new 532-hp 2026 Porsche 911 Carrera GTS with T-Hybrid technology.', 
  true, 
  13
);
